[cosmic-ray]
module-path = "pseudosnake"
python-version = ""
timeout = 30.0
excluded-modules = []

[cosmic-ray.execution-engine]
name = "local"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.cloning]
method = "copy"
commands = []

[cosmic-ray.test-command]
command = "pytest tests/"
